[versions]
agp = "8.13.2"

# AndroidX / UI
appcompat = "1.6.1"
activity = "1.9.3"
constraintlayout = "2.1.4"
material = "1.12.0"
gridlayout = "1.0.0"
recyclerview = "1.3.2"

# Lifecycle
lifecycle = "2.8.6"

# Navigation
navigation = "2.7.7"

# Networking
retrofit = "2.11.0"
okhttpLogging = "4.12.0"

# Glide
glide = "4.16.0"

# Tests
junit4 = "4.13.2"
extJunit = "1.2.1"
espresso = "3.6.1"

[libraries]
# AndroidX / UI
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

# Lifecycle
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }

# Navigation
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }

# Networking
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }

# Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Tests
junit4 = { module = "junit:junit", version.ref = "junit4" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
